source 'http://www.rubygems.org'
gem 'cucumber', '3.1.2'
gem 'rspec'
gem 'watir'
gem 'webdrivers'
gem 'rake'
gem 'page-object'
gem 'selenium-webdriver', '3.4.0'
gem 'config'
gem 'diff_match_patch'
gem 'json'
gem 'nokogiri'
gem 'parallel_tests'
gem 'report_builder'