default: --format pretty -p html_report --color
start: --format pretty -p jenkins --color
html_report: --format html --out report.html
jenkins: --format pretty -p json_report
json_report: --format json --out report.json
chrome: DRIVER=chrome
 